version: "3.8"

services:
  #  mssql:
  #    image: mcr.microsoft.com/mssql/server:2019-latest
  #    container_name: mssql
  #    ports:
  #      - "1433:1433"
  #    environment:
  #      SA_PASSWORD: "YourStrong@Passw0rd"
  #      ACCEPT_EULA: "Y"
  #    volumes:
  #      - mssql_data:/var/opt/mssql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YourRootPassword
      MYSQL_DATABASE: YourDatabaseName
      MYSQL_USER: YourUsername
      MYSQL_PASSWORD: YourPassword
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
#volumes:
#  mssql_data:
#    driver: local
